### ISSUE TITLE
qes

### ISSUE THREAD

**Issue by Lxunyu** [Lxunyu/web#3]
目的：在一个div中的每行最后一个dd去掉右边框
实现：比较每行dd与div的宽度，通过ref获取dom元素的集合，使用element.clineWidth获取宽度
问题：同样的代码一个可以实现另一个却不行

**Comment by kchanlee** [comment]
具体是哪段代码有问题？标出来。期望的结果是什么？实际的结果是什么？贴一些截图。

**Comment by Lxunyu** [comment]
具体代码在src/components/Question
期望结果
<img width="176" alt="result" src="https://user-images.githubusercontent.com/35958851/80577994-67a7ae00-8a3a-11ea-87f7-952d9da64f30.png">
实际结果
<img width="172" alt="one" src="https://user-images.githubusercontent.com/35958851/80579625-f1587b00-8a3c-11ea-8aca-3316183e2c30.png">

昨天还是一个可以实现一个不可以，今天都不行了

**Comment by kchanlee** [comment]
编译运行你的test branch，F12看到非常多的错误，先把这些修掉再说。
![image](https://user-images.githubusercontent.com/2238607/80586374-7052b100-8a47-11ea-86f4-499d3005907b.png)

**Comment by Lxunyu** [comment]
<img width="327" alt="2" src="https://user-images.githubusercontent.com/35958851/80587563-5ade8680-8a49-11ea-9a0b-c73ba539b09d.png">

**Comment by kchanlee** [comment]
问题原因见 #4

**Comment by Lxunyu** [comment]
收到
